CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Werror=vla -pedantic -g -lm

SRCS = prato.c heap.c cozinha.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean

all: cozinha

cozinha: $(OBJS)
			$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
		$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f cozinha $(OBJS)
