CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Werror=vla -pedantic -g -lm

SRCS = crianca.c familia.c hash.c halloween.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean

all: halloween

halloween: $(OBJS)
			$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
		$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f halloween $(OBJS)
