CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Werror=vla -pedantic -g -lm

SRCS = fila.c pilha.c grafo.c redecomep.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean

all: redecomep

redecomep: $(OBJS)
			$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
		$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f redecomep $(OBJS)
