CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Werror=vla -pedantic -g -lm

SRCS = che_flamenguista.c dracarys.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean

all: dracarys

dracarys: $(OBJS)
			$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
		$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f dracarys $(OBJS)
