CC = gcc
CFLAGS = -std=c99 -Wall -Werror -Werror=vla -pedantic -g -lm

SRCS = pilha.c arvore_binaria.c expressoes.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean

all: expressoes

expressoes: $(OBJS)
			$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
		$(CC) $(CFLAGS) -c -o $@ $<

clean: 
	rm -f expressoes $(OBJS)
